name: KiCAD Production Workflow

on:
  push:
#    paths:
#      - '**.sch'
#      - '**.kicad_pcb'
    pull_request:
      paths:
        - '**.sch'
        - '**.kicad_pcb'

jobs:
  panelize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Output Directory
        run: mkdir -p output

      - name: Panelization
        run: >
          docker run --rm -v ${{ github.workspace }}:/kikit yaqwsx/kikit
          panelize
          -p panel.json
          udb-s.kicad_pcb
          output/kicad

      - name: Create Production Files (JLCPCB)
        run: >
          docker run --rm -v ${{ github.workspace }}:/kikit yaqwsx/kikit
          fab
          jlcpcb 
          --assembly
          --schematic udb-s.kicad_sch
          output/production/jlcpcb

      - name: Upload Panel and Production Files
        uses: actions/upload-artifact@v4
        with:
          path: output
