name: KiCAD Production Workflow

on:
  push:
#    paths:
#      - '**.sch'
#      - '**.kicad_pcb'
    pull_request:
      paths:
        - '**.sch'
        - '**.kicad_pcb'

jobs:
  panelize:
    runs-on: ubuntu-latest
    services:
      kikit:
        image: yaqwsx/kikit
        options: >
          --name kikit-container 
          -v ${{ github.workspace }}:/workspace
          tail -f /dev/null
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Panelize
        run: |
          docker exec kikit-container kikit --help
