name: KiCAD Production Workflow

on:
  push:
#    paths:
#      - '**.sch'
#      - '**.kicad_pcb'
    pull_request:
      paths:
        - '**.sch'
        - '**.kicad_pcb'

jobs:
  panelize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run:
          echo ${{ github.workspace }} && pwd && ls -la ${{ github.workspace }}

      - name: Panelize
        run: >
          docker run --rm 
          -v ${{ github.workspace }}:/kikit 
          yaqwsx/kikit panelize --preset panel.json udb-s.kicad_pcb /workplace/panel.kicad_pcb
