name: KiCAD Production Workflow

on:
  push:
#    paths:
#      - '**.sch'
#      - '**.kicad_pcb'
    pull_request:
      paths:
        - '**.sch'
        - '**.kicad_pcb'

jobs:
  panelize:
    strategy:
      matrix:
        panel_rows: [2, 3]
        panel_cols: [8, 10]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Output Directories
        run: mkdir -p output/kicad/ output/production/jlcpcb/ output/production/pcbway/

      - name: Pull KiKit Docker Image
        run: docker pull yaqwsx/kikit

      - name: Panelization
        run: >
          docker run --rm -v ${{ github.workspace }}:/kikit yaqwsx/kikit
          panelize
          --preset panel.json
          --layout "rows: ${{ matrix.panel_rows }}; cols: ${{ matrix.panel_cols }}"
          udb-s.kicad_pcb
          output/kicad/panelized.kicad_pcb

      - name: Create Production Files (JLCPCB)
        run: >
          docker run --rm -v ${{ github.workspace }}:/kikit yaqwsx/kikit
          fab
          jlcpcb 
          --no-drc
          --assembly
          --schematic udb-s.kicad_sch
          output/kicad/panelized.kicad_pcb
          output/production/jlcpcb/

      - name: Upload Panel and Production Files
        uses: actions/upload-artifact@v4
        with:
          name: panel-${{ matrix.panel_rows }}x${{ matrix.panel_cols }}
          path: output
